Replace gpg --local-user and --default-key with --recipient
easternlabs/1password-backup pull request #2
Opened 2023-02-23 16:58 UTC by cmichelNGT

macos built GPG via homebrew doesn't seem to honor `--local-user and `--default-key`, but it does respect `--recipient`. This PR fixes that concern by replacing the arguments.

2023-02-27 19:24 UTC, numeratorjik requested changes

2023-02-27 19:24 UTC, numeratorjik commented on 1password-backup.py
> +                cmd.extend(['--recipient', args.key])
Delete the obsolete comment above this code!

2023-02-27 21:44 UTC, cmichelNGT commented
@numeratorjik Made the change, back over to you.

2023-02-28 16:35 UTC, numeratorjik approved these changes

2023-03-01 16:15 UTC, merged